тесты на пхп и гоу
Kolesa-Education/kolesa-upgrade-homework-11 pull request #18
Opened 2022-11-12 16:34 UTC by salawhaaat

тесты

2022-11-12 16:53 UTC, tungatarovKl requested changes
Логика есть, но теперь нужно добавить тесты которые будут проверят метод класса PaymentRequestValidator, которые должны находиться в tests/Validation/PaymentRequestValidatorTest.php

2022-11-12 16:53 UTC, tungatarovKl commented on src/Validation/PaymentRequestValidator.php
> +    public function testName( array $name):array {
этот метод ведь не тестирует, а проверяет

2022-11-12 16:53 UTC, tungatarovKl commented on src/Validation/PaymentRequestValidator.php
> +    public function testCard( string $card):array {
тоже название метода не должен начинаться с test, т.к вводить в заблуждение

2022-11-12 17:25 UTC, salawhaaat commented on src/Validation/PaymentRequestValidator.php
> +    public function testName( array $name):array {
isValidName ... вот так
 переименовать ?

2022-11-13 04:26 UTC, tungatarovKl requested changes
Тест не закончен!
Не работает при вызыве.
Нужно также добавить dataProvider так как без дата провайдер в твоем примере, аргументы $data, $expected не придут к тесту testValidation
Провайдеры данных описаны тут: https://phpunit.readthedocs.io/ru/latest/writing-tests-for-phpunit.html#writing-tests-for-phpunit-data-providers
Нужно проверить что тесты запускаются перед PR

2022-11-13 16:25 UTC, tungatarovKl approved these changes

2025-02-24 09:48 UTC, closed without merging